[package]
name = "egui_memory_viewer"
version = "0.1.0"
authors = ["Hirtol"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
serde_support = ["serde"]

[dependencies]
egui = "^0.8.0"


[dependencies.serde]
version = "^1.0.123"
features = ["derive"]
optional = true
