[package]
name = "egui_memory_editor"
version = "0.1.0"
authors = ["Hirtol <rust@hirtol.top>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
persistence = ["serde", "egui/persistence"]

[dependencies]
egui = "^0.9.0"

[dev-dependencies]
eframe = "^0.9.0"

[dependencies.serde]
version = "^1.0.123"
features = ["derive"]
optional = true
